### PR TITLE
Time change

### PR DESCRIPTION
**Pull request by rickecon**
For some reason, the benevolent dictator changed the time to a weird time. This PR changes the time back, adds "am" to 11:30, and deletes a weird file that somehow got pushed up to my branch.

### CODE REVIEW

**Comment by jtschoi** [comment]
Hello

**Comment by AZorroMedina** [comment]
Comment

**Comment by JiaxiLi1995** [comment]
Good change!

**Comment by zeyuxu1997** [comment]
Interesting

**Comment by jsgenan** [comment]
Woah

**Comment by xianNeuro** [comment]
hmmmm

**Pull request merged**
